### ISSUE TITLE
No module named 'opensimplex'

### ISSUE THREAD

**Issue by lockwoodgary** [openai/neural-mmo#13]
When trying to install, at the very last line 'python setup.py', getting the above error. I'm on Win10, have conda installed (python 3.7). Didn't have any problems installing in the neural-mmo-client folder. For the neural-mmo folder, I used the Git command 'sh scripts/setup/setup.py' for the bash install. Any ideas where it went wrong?

**Comment by jsuarez5341** [comment]
Opensimplex is included in the setup script dependencies. Windows is not officially supported -- it might work, but it's not going to be an out-of-the-box experience. Closing for now -- feel free to reopen if you really want to get it working on windows...there's some discussion of this on reddit. You'll have to delete the ray hooks, which means you will need to roll your own distributed code if you want to train at scale. Feel free to post the full output of "python setup.py"

**Comment by oveddan** [comment]
I have the same issue. I'm on OSX and followed the instructions in the readme.  I'm using Anaconda, and ran `pythonw setup.py`

 Here is the message:

"Requirement already satisfied: jsonpickle in /anaconda3/envs/agents/lib/python3.7/site-packages (1.1)
Requirement already satisfied: opensimplex in /anaconda3/envs/agents/lib/python3.7/site-packages (0.2)
Requirement already satisfied: twisted in /anaconda3/envs/agents/lib/python3.7/site-packages (18.9.0)
Requirement already satisfied: Automat>=0.3.0 in /anaconda3/envs/agents/lib/python3.7/site-packages (from twisted) (0.7.0)
Requirement already satisfied: PyHamcrest>=1.9.0 in /anaconda3/envs/agents/lib/python3.7/site-packages (from twisted) (1.9.0)
Requirement already satisfied: zope.interface>=4.4.2 in /anaconda3/envs/agents/lib/python3.7/site-packages (from twisted) (4.6.0)
Requirement already satisfied: attrs>=17.4.0 in /anaconda3/envs/agents/lib/python3.7/site-packages (from twisted) (19.1.0)
Requirement already satisfied: incremental>=16.10.1 in /anaconda3/envs/agents/lib/python3.7/site-packages (from twisted) (17.5.0)
Requirement already satisfied: constantly>=15.1 in /anaconda3/envs/agents/lib/python3.7/site-packages (from twisted) (15.1.0)
Requirement already satisfied: hyperlink>=17.1.1 in /anaconda3/envs/agents/lib/python3.7/site-packages (from twisted) (18.0.0)
Requirement already satisfied: six in /anaconda3/envs/agents/lib/python3.7/site-packages (from Automat>=0.3.0->twisted) (1.12.0)
Requirement already satisfied: setuptools in /anaconda3/envs/agents/lib/python3.7/site-packages (from PyHamcrest>=1.9.0->twisted) (40.8.0)
Requirement already satisfied: idna>=2.5 in /anaconda3/envs/agents/lib/python3.7/site-packages (from hyperlink>=17.1.1->twisted) (2.8)
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import terrain
  File "/Users/danoved/Source/world-agents/neural-mmo/terrain.py", line 2, in <module>
    from opensimplex import OpenSimplex
ImportError: No module named opensimplex"

**Comment by oveddan** [comment]
Ok I resolved this.
Originally I was trying to do python setup.py
but ran into an error:

> ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information

I found a [similar issue](https://github.com/scikit-optimize/scikit-optimize/issues/637) in openai gym, and fixed it by running:
`conda install matplotlib`
