### ISSUE TITLE
No module named 'forge.embyr'

### ISSUE THREAD

**Issue by 623059008** [openai/neural-mmo#19]
Hi, it is a really awsome project. I want to setup it on my server.
And following the instructions I have installed all dependencies.
But when I run 
```
python3 Forge.py --render
```
It occurs errors.
```
Traceback (most recent call last):
  File "Forge.py", line 72, in <module>
    example.env.render()
  File "/root/mmo/neural-mmo/forge/trinity/smith.py", line 57, in render
    from forge.embyr.twistedserver import Application
ModuleNotFoundError: No module named 'forge.embyr'
```
![](https://i.loli.net/2019/03/18/5c8f8a90a3e8c.jpg)

**Comment by shuruiz** [comment]
There should be something wrong when you were installing neural-mmo. You missed this file: 
https://github.com/openai/neural-mmo/blob/master/forge/embyr

you can check your neural-mmo repo to see if it exists. If not, I will recommend you either copy the script to the repo or re-setup.

**Comment by jsuarez5341** [comment]
One of two things probably happened. Reopen if it end up being something else.
1. You didn't install the client separately. There is another repo you have to clone (neural-mmo-client).
2. A symlink broke on your machine. forge/embyr is a symlink to the client repo. This shouldn't happen, but if this is the case, just fix the symlink locally.

**Comment by heyCarlH** [comment]
I am having the same issue. I have completely reinstall both the mmo and the client. Are there any other solutions?

**Comment by tempest2023** [comment]
> I am having the same issue. I have completely reinstall both the mmo and the client. Are there any other solutions?

Yes, I solved this problem.
I make a symlink from 'neural-mmo-client' to 'neural-mmo/forge/embyr'.

**Comment by heyCarlH** [comment]
Thanks.
