### ISSUE TITLE
Help :  No module named 'ray'

### ISSUE THREAD

**Issue by cndavy** [openai/neural-mmo#2]
(tensorflow) D:\git\projekt\neural-mmo>python setup.py
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import terrain
  File "D:\git\projekt\neural-mmo\terrain.py", line 5, in <module>
    from forge.blade.lib import enums
  File "D:\git\projekt\neural-mmo\forge\blade\lib\__init__.py", line 4, in <module>
    from .ray import init
  File "D:\git\projekt\neural-mmo\forge\blade\lib\ray.py", line 1, in <module>
    import ray, os
ModuleNotFoundError: No module named 'ray'

**Comment by cclauss** [comment]
$ __pip install -r scripts/setup/requirements.txt__
* https://github.com/openai/neural-mmo/search?l=Text&q=ray

**Comment by cndavy** [comment]
> $ **pip install -r scripts/setup/requirements.txt**
> 
> * https://github.com/openai/neural-mmo/search?l=Text&q=ray
 Thank U  ,I just found the shell
#Pytorch
pip install http://download.pytorch.org/whl/cu90/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
pip install torchvision

#Ray -- will segfault in .backward with wrong version
#pip uninstall -y ray
#pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/68b11c8251dc41e79dc9dc4b1da31630708a6bd8/ray-0.4.0-cp36-cp36m-manylinux1_x86_64.whl

#Ray
pip install ray
pip install setproctitle
pip install service_identity

#Basics
pip install numpy
pip install scipy
pip install matplotlib


#Tiled map loader
pip install pytmx

#jsonpickle
pip install jsonpickle
pip install opensimplex
pip install twisted

**Comment by katnoria** [comment]
or just run setup.sh script under scripts/setup from <your_repo_root_dir>
```
sh scripts/setup/setup.sh
```

**Comment by jsuarez5341** [comment]
This has been added to the setup. Please reopen if setup errors persist.

**Comment by m-bouville** [comment]
Can you clarify what part requires 'ray' and what can still run without it? cf. https://news.ycombinator.com/item?id=16512784
