### ISSUE TITLE
Page stuck

### ISSUE THREAD

**Issue by tonghaining** [openai/neural-mmo#23]
After I run
`python Forge.py`
Terminal shows out:
` python Forge.py --render
testlaw128 , NENT:  128 , NPOP:  8
testchaos128 , NENT:  128 , NPOP:  8
sample , NENT:  128 , NPOP:  8
Enabling local test mode for render
Initializing new model...
Loading model...
#Params:  1484.264 K
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Uptime:  0.6 , Tick:  1
Uptime:  1.2 , Tick:  2
Uptime:  1.8 , Tick:  3
Uptime:  2.4 , Tick:  4
Uptime:  3.0 , Tick:  5
Uptime:  3.6 , Tick:  6
Uptime:  4.2 , Tick:  7
Uptime:  4.8 , Tick:  8
Created a server
WebSocket connection request: {"peer": "tcp4:127.0.0.1:37968", "headers": {"host": "localhost:8080", "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0", "accept": "*/*", "accept-language": "en-US,en;q=0.5", "accept-encoding": "gzip, deflate", "sec-websocket-version": "13", "origin": "http://localhost:8080", "sec-websocket-extensions": "permessage-deflate", "sec-websocket-key": "IZS4kvPcZ2OdzO76g41ohg==", "connection": "keep-alive, Upgrade", "pragma": "no-cache", "cache-control": "no-cache", "upgrade": "websocket"}, "host": "localhost", "path": "/ws", "params": {}, "version": 13, "origin": "http://localhost:8080", "protocols": [], "extensions": [["permessage-deflate", {}]]}
Opened connection to server
Uptime:  5.4 , Tick:  9
Uptime:  6.0 , Tick:  10
Uptime:  6.6 , Tick:  11
Uptime:  7.2 , Tick:  12
Uptime:  7.8 , Tick:  13
Uptime:  8.4 , Tick:  14
Uptime:  9.0 , Tick:  15
Uptime:  9.6 , Tick:  16
Uptime:  10.2 , Tick:  17
Uptime:  10.8 , Tick:  18
`
But the page of [http://localhost:8080/forge/embyr/](url) are shown as
![Screenshot from 2019-04-06 14-57-19](https://user-images.githubusercontent.com/22913076/55669822-55316400-587c-11e9-971d-0cd4e5564126.png)

And no reaction whatever I click.

**Comment by jsuarez5341** [comment]
I'll need some additional information in order to help

1. Do you get any errors running without --render (this will just hang until you kill it, but the renderer sometimes surpresses obvious server error messages)

2. Does the Web Developer mode on Firefox show any errors?

**Comment by tonghaining** [comment]
1. Below is the output without --render of `python Forge.py`:
![Screenshot from 2019-04-07 09-09-06](https://user-images.githubusercontent.com/22913076/55680043-f835bc80-5914-11e9-9aac-edefa50cdc96.png)

2. Yes, 
![Screenshot from 2019-04-07 09-07-33](https://user-images.githubusercontent.com/22913076/55680011-a68d3200-5914-11e9-9793-108b07cef9eb.png)

**Comment by jsuarez5341** [comment]
Oh, you're just missing three.js. Did you run the setup for the client? This should just download it for you.

**Comment by jsuarez5341** [comment]
Glad to help
