### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by jiang910622** [openai/neural-mmo#25]
It seems that neural-mmo is not available at Windows, due to the difficulties with the Ray library. Is there any way to solve it?

**Comment by jsuarez5341** [comment]
Yes, check issue 21 -- It's not supported out of the box, but it is fairly straightforward to strip out Ray references. I'll look into this in an official capacity in the future, but I am currently the only dev, and I'm prioritizing my efforts towards the first major patch

**Comment by amelkikh** [comment]
> Yes, check issue 21 -- It's not supported out of the box, but it is fairly straightforward to strip out Ray references. I'll look into this in an official capacity in the future, but I am currently the only dev, and I'm prioritizing my efforts towards the first major patch

Will you further explore this issue?
Regards.
