### ISSUE TITLE
pip install $pkg --user

### ISSUE THREAD

**Issue by AshtonHarding** [openai/neural-mmo#26]
Since (at least for some people) pip requires `--user` and while I'm sure there is a better way to do this: 

`cat neural-mmo/scripts/setup/setup.sh | grep "pip" | sed 's/$/ --user/' | bash`

Where would be the best place to put this information? I know it's trivial but it's a lot better than editing line by line. Could we have a wiki with tips or something of that sort?

**Comment by jsuarez5341** [comment]
Just noticed this -- sorry! Yeah, there's a bunch of setup stuff that needs a home. I'll leave this open so I know integrate it in the next patch. I don't exactly have the bandwidth to maintain a full wiki at the moment, but I'll definitely take a pass at the readme setup when I finally finish this patch

**Comment by jsuarez5341** [comment]
The new patch, which will be live in a day or two, has a requirements.txt. pip install -r --user will work for the new version.
