### ISSUE TITLE
Issue on file tile.py unreachable return statement

### ISSUE THREAD

**Issue by DanielTellier** [openai/neural-mmo#28]
Error is at lines 45 through 47 not sure what should be indented.

```python
def harvest(self):
      if self.capacity == 0:
         return False
      elif self.capacity <= 1:
         self.state = self.mat.degen()
      self.capacity -= 1
      return True
      return self.mat.dropTable.roll()
```

**Comment by jsuarez5341** [comment]
Dumb but intended. There are a bunch of backlog content features I plan on implementing in the second patch (first one, which I'm working on now, is around infra, IO, scale, and ethyr API). A lot of these dumb things will go away then -- keeping them as placeholders for now
