### ISSUE TITLE
Logs don't get updated

### ISSUE THREAD

**Issue by frenzytejask98** [openai/neural-mmo#32]
The logs folder doesn't update. Moreover how to generate models for 16, 35, 64, etc agents. I am only able to run it for 128 number of agents as I don't have example models for the rest. @jsuarez5341 please help.

**Comment by jsuarez5341** [comment]
Hi! If you check the configs.py and experiments.py, you'll notice that the default setup is running in test mode to show off the demo model. The demo was trained with 128 agents -- experiments.py has short (though admittedly messy) example code for setting training parameters, including population size. Logs and models are written to resource/exps (I forgot to remove the logs directory from a previous version and nobody has mentioned it until now). Feel free to reopen if you are still having issues

Also, it's worth mentioning we're only a day or two out from the first major patch. Ideally it will help clear up most of the confusion. I'll add better config docs to my todos for today.
