### ISSUE TITLE
Not able to run the experiments.

### ISSUE THREAD

**Issue by frenzytejask98** [openai/neural-mmo#34]
How do I run the Forge for a different amount of participants. I tried changing values in experiments.py but it just makes empty folders in the resources/exps.

This is the error I run into when I run Forge.py
FileNotFoundError: [Errno 2] No such file or directory: 'resource/exps/testchaos128/model/bests.pth'

**Comment by jsuarez5341** [comment]
We just updated to 1.1, a new major version. That path looks like it's from 1.0. In either case, the demo policy was trained with 128 agents. You can disable the test time options (load/test/best) in config to train a new policy from scratch with a different population size. It probably won't perform as well, but you can also load the demo policy with a different number of agents by changing NENT in experiments. In the v1.0 release, you'd also have to modify experiments.py to hardcode the demo bests.pth path.

Please note that as of 1.1, we have a Discord server (https://discordapp.com/invite/BkMmFUC) for further support
