### ISSUE TITLE
Agent pass the stone

### ISSUE THREAD

**Issue by wwxFromTju** [openai/neural-mmo#5]
Hi,  when i try to render the env, I find that agent pass the stone.

![2019-03-05 6 42 40](https://user-images.githubusercontent.com/14865611/53799981-ae089680-3f76-11e9-87ae-8267fcccc92e.png)
![2019-03-05 6 42 14](https://user-images.githubusercontent.com/14865611/53800029-ce385580-3f76-11e9-9030-4f2db653ff59.png)

**Comment by jsuarez5341** [comment]
Odd. I haven't observed that. Is this consistent, or on loadup in the middle of a lagspike? Want to make sure it's just not "teleporting" through due to skipping a few frames before looking deeper

**Comment by wwxFromTju** [comment]
I first run: `python Forge.py --render`
Then use chrome to enter: http://localhost:8080/forge/embyr/
Log info is below:

```
reated a server
WebSocket connection request: {"peer": "tcp4:127.0.0.1:53419", "headers": {"host": "127.0.0.1:8080", "connection": "Upgrade", "pragma": "no -cache", "cache-control": "no-cache", "upgrade": "websocket", "origin": "http://localhost:8080", "sec-websocket-version": "13", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36", "accept-encoding": "gzip, deflate, br ", "accept-language": "zh-CN,zh;q=0.9", "sec-websocket-key": "Qky+LY2S8jvF72mWPdgIyw==", "sec-websocket-extensions": "permessage-deflate; client_max_window_bits "}, "host": "127.0.0.1", "path": "/ws", "params": {}, "version": 13, "origin": "http://localhost:8080", " Protocols:: [], "extensions": [["permessage-deflate", {"client_max_window_bits": [true]}]]}
Opened connection to server
```
![2019-03-06 7 14 18](https://user-images.githubusercontent.com/14865611/53877751-f68e8580-4044-11e9-956f-185c47bf634f.png)
![2019-03-06 7 12 37](https://user-images.githubusercontent.com/14865611/53877770-04440b00-4045-11e9-9932-5fe2e45fe1a4.png)

Then I use wsad or up, down, left, right for fun, than find agent pass the stone.
For example below:

I didn't just use zoom in and out to see the map.

I observed that the Forest near the agent is occasionally collected. I think the agent may drift when it is a render.

**Comment by jsuarez5341** [comment]
Ah okay, good. I was going to say, I'm fairly positive it's correct in the underlying environment. Probably at worse a 1 tick desync or off by 1 error in the renderer. Traveling ATM, but I'll look into it over the next few days. If you happen to find it before me, feel free to submit a PR to the client repo

**Comment by shyamsn97** [comment]
I've observed a similar issue. It seems to happen consistently when I render the env.
![Screen Shot 2019-03-10 at 10 44 34 PM](https://user-images.githubusercontent.com/18158178/54102673-a423d080-4386-11e9-8308-51bef19f5e42.png)

**Comment by jsuarez5341** [comment]
Alright, well aware of this now. Again, probably an off by 1 in the renderer. Will look into this as soon as I get a chance.

**Comment by jsuarez5341** [comment]
I'm only able to reproduce this during intentionally induced lag spikes (expected behavior -- if you miss a few ticks, agents move in a direct line to their final position). Tried wasd, arrow keys, mouse control -- nothing seems to cause this behavior after about 15-20 minutes of testing. I'm getting 50 FPS on Firefox and double that on Chrome. I'm thinking there might be some weird lag induced desync on lower end systems. What frame rates are you getting after the environment has warmed up and there are agents all over the map?

**Comment by kumarict** [comment]
I added manual control for one of the agents and found that the position in the view is off by one in x and off by one in y as compared to the model. Perhaps there is an off-by-one error? The game would pause after every tick and await user input, so it may not be frame rate related.

**Comment by wwxFromTju** [comment]
yep, I fix it by: https://github.com/openai/neural-mmo/pull/22

**Comment by m-bouville** [comment]
The same happens with lava:
![in_lava](https://user-images.githubusercontent.com/7511636/56019450-eb460e00-5d04-11e9-9661-c4246eb11ee0.png)
What is not obvious from a still image is that some of the agents will then die but some others will come back to land safe and sound.

**Comment by wwxFromTju** [comment]
@m-bouville try this: https://github.com/openai/neural-mmo/pull/22

**Comment by jsuarez5341** [comment]
Just FYI -- have not forgotten about this, just got caught up with the awesome DotA result and working on the first major environment patch. You're probably right that I'm using a different code version. I'll likely bundle this fix with the patch once I get to it

**Comment by jsuarez5341** [comment]
Well, something is really screwy here. I just made sure I was on the same code version (redid set up from scratch), tested both Chrome and Firefox, and I still can't reproduce the issue. If you are _not_ getting this error, please post to let me know -- I'd like to know if it's on my end (despite testing on multiple machines) or if it's setup dependent.

**Comment by jsuarez5341** [comment]
Update: spent a long time trying to reproduce this, have tested on multiple machines, firefox + chrome ... it's gone in 1.1. Otherwise reopen.
